package com.ajohnson.dlparserkotlin.models

/**
 * Keys used to map license data to the license model.
 */
internal enum class FieldKey {
    FIRST_NAME,
    LAST_NAME,
    MIDDLE_NAME,

    DRIVER_LICENSE_NAME,
    GIVEN_NAME,

    LAST_NAME_ALIAS,
    FIRST_NAME_ALIAS,
    GIVEN_NAME_ALIAS,
    SUFFIX_ALIAS,
    SUFFIX,

    MIDDLE_NAME_TRUNCATION,
    FIRST_NAME_TRUNCATION,
    LAST_NAME_TRUNCATION,

    EXPIRATION_DATE,
    ISSUE_DATE,
    BIRTH_DATE,
    HAZMAT_EXPIRATION_DATE,
    REVISION_DATE,

    RACE,
    GENDER,
    EYE_COLOR,
    HEIGHT_INCHES,
    HEIGHT_CENTIMETERS,
    HAIR_COLOR,
    WEIGHT_RANGE,
    WEIGHT_POUNDS,
    WEIGHT_KILOGRAMS,

    PLACE_OF_BIRTH,
    STREET_ADDRESS,
    STREET_ADDRESS_TWO,
    CITY,
    STATE,
    POSTAL_CODE,
    COUNTRY,

    DRIVER_LICENSE_NUMBER,
    UNIQUE_DOCUMENT_ID,
    AUDIT_INFORMATION,
    INVENTORY_CONTROL_NUMBER,
    COMPLIANCE_TYPE,

    IS_ORGAN_DONOR,
    IS_VETERAN,
    IS_TEMPORARY_DOCUMENT,

    FEDERAL_VEHICLE_CODE,

    STANDARD_VEHICLE_CODE,
    STANDARD_RESTRICTION_CODE,
    STANDARD_ENDORSEMENT_CODE,

    JURISDICTION_VEHICLE_CLASS,
    JURISDICTION_RESTRICTION_CODE,
    JURISDICTION_ENDORSEMENT_CODE,

    JURISDICTION_VEHICLE_CLASS_DESCRIPTION,
    JURISDICTION_RESTRICTION_CODE_DESCRIPTION,
    JURISDICTION_ENDORSEMENT_CODE_DESCRIPTION,

    FEDERAL_COMMERCIAL_VEHICLE_CODE;
}